name: Publish PyPi package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install setuptools wheel twine
      - name: Run tests
        run: pytest 
      - name: Build and publish to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_GOLDENOWL_UPLOAD_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
